server: # Server port number to run gateway API
    port: 8085

spring: # Connection details to other microservices
    cloud:
        gateway:
            routes:
            - id: order-service
              uri: lb://ORDER-SERVICE/
              predicates:
              - Path=/orders/**
              filters:
              - name: CircuitBreaker
                args:
                    name: order-service
                    fallbackuri: forward:/orderFallBack
            
            - id: payment-service
              uri: lb://PAYMENT-SERVICE/
              predicates:
              - Path=/payment/**
              filters:
              - name: CircuitBreaker
                args:
                  name: payment-service
                  fallbackuri: forward:/paymentFallBack

    application: # Tag to view in Eureka web page
        name: GATEWAY-SERVICE

eureka: # Connecting gateway to main server
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost

# Following settings used in tandem with Hystrix
management:
    endpoints:
        web:    
            exposure:
                include: hystrix.stream

hystrix:
    command:
        fallbackcmd:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 1500
